"""added a column to the  users table

Revision ID: 218955efb432
Revises: d81dd17aa954
Create Date: 2018-09-13 11:34:50.152492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218955efb432'
down_revision = 'd81dd17aa954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
